language: java
jdk:
  - openjdk7
  - oraclejdk7
before_install:
  - cd code/mlmq
  - cp resource/brokerconfig.example.properties resource/brokerconfig.properties
  - cp resource/clientconfig.example.properties resource/clientconfig.properties
before_script:
  - psql -c 'create database mlmq;' -U postgres
  - psql -c "alter role postgres with password 'postgres';" -U postgres 
script:
  - mvn test -B -e
